### ISSUE TITLE
Plaintext API key

### ISSUE THREAD

**Issue by augustus-thomas** [JMacT/Unit_converter#2]
saw this project from a branch your brother made of it. idk if you care cousin but your currency api key from 5 years ago is in plain text in the data.py file. usually people use a .gitignore file to manage secrets and you can declare various env variables in an env directory and then .gitignore it. again idk if you care though just wanted to troll you :)) see you this summer

we should collaborate on some aps sometime

**Comment by JMacT** [comment]
You are the man, Gus!
I have no idea what kind of security issues that I'm incurring here. I really thought these repos were private lol.

Nice commits by the way! It looks like you fixed the issue you're referring to? Do I just have to merge it and then close this out with resolved?

Thanks!

**Comment by augustus-thomas** [comment]
Lol no worries, I'm glad to help!

You can merge the commits to the main branch through my pull request. There should be a green buttons somewhere that says "merge changes" or the like. 

I am going to add something to the README.md file today because installation of the project is a little more in-depth now. Now after cloning one has to manually add a env/.env file that has a line in it declaring the api key. If I get time Ill do that today.

**Comment by augustus-thomas** [comment]
I found this source for removing the history of your secret being on GitHub. Idrk if it really matters that much or how this works. [link to GitHub article](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository)
